
/**
 *
 * @author Unknown
 */
public class DetailForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DetailForm.class.getName());

    /**
     * Creates new form DetailForm
     */
    public DetailForm() {
        initComponents();
        setSize(800, 600);           // 창 크기 설정 (가로 800, 세로 600 픽셀)
        setLocationRelativeTo(null); // 창을 모니터 화면 중앙에 배치
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        valName = new javax.swing.JLabel();
        lblNameTag = new javax.swing.JLabel();
        lblDonorTag = new javax.swing.JLabel();
        valDonor = new javax.swing.JLabel();
        valStatus = new javax.swing.JLabel();
        lblStatusTag = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lbl = new javax.swing.JLabel();
        btnApply = new javax.swing.JButton();
        btnList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        valName.setFont(new java.awt.Font("휴먼편지체", 0, 36)); // NOI18N
        valName.setText("(실제 물품명)");

        lblNameTag.setFont(new java.awt.Font("휴먼편지체", 0, 36)); // NOI18N
        lblNameTag.setText("물품명 :");

        lblDonorTag.setFont(new java.awt.Font("휴먼편지체", 0, 36)); // NOI18N
        lblDonorTag.setText("기부자 :");

        valDonor.setFont(new java.awt.Font("휴먼편지체", 0, 36)); // NOI18N
        valDonor.setText("(실제 기부자ID)");

        valStatus.setFont(new java.awt.Font("휴먼편지체", 0, 36)); // NOI18N
        valStatus.setText("(판매중/예약중)");

        lblStatusTag.setFont(new java.awt.Font("휴먼편지체", 0, 36)); // NOI18N
        lblStatusTag.setText("상태   :");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        lbl.setFont(new java.awt.Font("휴먼편지체", 0, 36)); // NOI18N
        lbl.setText("설명 : ");

        btnApply.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        btnApply.setText("나눔 신청하기");

        btnList.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        btnList.setText("< 목록으로");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnList)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnApply))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNameTag)
                            .addComponent(lblDonorTag)
                            .addComponent(lblStatusTag))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(valName, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(valStatus, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(valDonor, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnList)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameTag)
                    .addComponent(valName))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valDonor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDonorTag))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatusTag)
                    .addComponent(valStatus))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnApply)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DetailForm().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblDonorTag;
    private javax.swing.JLabel lblNameTag;
    private javax.swing.JLabel lblStatusTag;
    private javax.swing.JLabel valDonor;
    private javax.swing.JLabel valName;
    private javax.swing.JLabel valStatus;
    // End of variables declaration                   
}
